### ISSUE TITLE
redis didnt connect

### ISSUE THREAD

**Issue by andysay** [wpcodevo/golang-fiber-jwt-rs256#1]
panic: NOAUTH HELLO must be called with the client already authenticated, otherwise the HELLO AUTH <user> <pass> option can be used to authenticate the client and select the RESP protocol version at the same time

**Comment by wpcodevo** [comment]
> panic: NOAUTH HELLO must be called with the client already authenticated, otherwise the HELLO AUTH option can be used to authenticate the client and select the RESP protocol version at the same time

If you're encountering Redis-related issues with the project on a particular operating system, I recommend attempting to run the project on a different OS, such as Windows, Ubuntu, or Mac. 

Please note that the project has been tested and runs smoothly on my Windows WSL environment. 

If you continue to experience issues with other operating systems, please don't hesitate to contact me for further assistance.

**Comment by andysay** [comment]
@wpcodevo Hello, and thx for response! i'm using MacOS 12.6 with Docker 

<img width="1695" alt="Снимок экрана 2023-02-18 в 12 54 40" src="https://user-images.githubusercontent.com/5610952/219878171-36e861c2-6f9d-4bec-99e3-3f38e85d13af.png">

REDIS: 7.0.5

**Comment by andysay** [comment]
on top of the docker there was a another redis to which he connected
